package com.rawbridge.app.ui.theme

import androidx.compose.ui.graphics.Color

val RawBridgePrimary = Color(0xFF315F87)
val RawBridgeOnPrimary = Color(0xFFFFFFFF)
val RawBridgePrimaryContainer = Color(0xFFD4E7F7)
val RawBridgeOnPrimaryContainer = Color(0xFF0F2438)
val RawBridgePrimaryDark = Color(0xFFA3C9F0)
val RawBridgeOnPrimaryDark = Color(0xFF06233B)
val RawBridgePrimaryContainerDark = Color(0xFF214667)
val RawBridgeOnPrimaryContainerDark = Color(0xFFD4E7F7)

val RawBridgeSecondary = Color(0xFF5B6470)
val RawBridgeOnSecondary = Color(0xFFFFFFFF)
val RawBridgeSecondaryContainer = Color(0xFFE0E5EB)
val RawBridgeOnSecondaryContainer = Color(0xFF1A1E24)
val RawBridgeSecondaryDark = Color(0xFFC0C8D2)
val RawBridgeOnSecondaryDark = Color(0xFF26303A)
val RawBridgeSecondaryContainerDark = Color(0xFF404955)
val RawBridgeOnSecondaryContainerDark = Color(0xFFE0E5EB)

val RawBridgeBackground = Color(0xFFF5F7FA)
val RawBridgeSurface = Color(0xFFFFFFFF)
val RawBridgeSurfaceVariant = Color(0xFFE9EDF2)
val RawBridgeOnSurface = Color(0xFF191C20)
val RawBridgeOnSurfaceVariant = Color(0xFF5A616A)
val RawBridgeOutline = Color(0xFFB4BCC6)
val RawBridgeError = Color(0xFFB3261E)
val RawBridgeErrorContainer = Color(0xFFF9DEDC)
val RawBridgeOnErrorContainer = Color(0xFF410E0B)
val RawBridgeBackgroundDark = Color(0xFF0F1317)
val RawBridgeSurfaceDark = Color(0xFF171B20)
val RawBridgeSurfaceVariantDark = Color(0xFF232A31)
val RawBridgeOnSurfaceDark = Color(0xFFE6EAF0)
val RawBridgeOnSurfaceVariantDark = Color(0xFFB5BEC8)
val RawBridgeOutlineDark = Color(0xFF59636E)
val RawBridgeErrorDark = Color(0xFFFFB4AB)
val RawBridgeOnErrorDark = Color(0xFF690005)
val RawBridgeErrorContainerDark = Color(0xFF93000A)
val RawBridgeOnErrorContainerDark = Color(0xFFFFDAD6)
